version: 0.1

phases:

  install:
    commands:
      - go get github.com/Masterminds/glide
      - glide install

  pre_build:
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o goname

artifacts:
  files:
    - main.go
    - buildspec.yml
    - languages/*

