package goname

func mapit(syllables []Syllable) map[string]Syllable {
	mymap := make(map[string]Syllable)
	for _, v := range syllables {
		mymap[v.text] = v
	}
	return mymap
}

// Elven language Syllables
var Elven = []Syllable{
	SyllableFactory("-Ael"),
	SyllableFactory("-Aer"),
	SyllableFactory("-af"),
	SyllableFactory("-ah"),
	SyllableFactory("-am"),
	SyllableFactory("-ama"),
	SyllableFactory("-an"),
	SyllableFactory("-ang +v"),
	SyllableFactory("-ansr +v"),
	SyllableFactory("-cael"),
	SyllableFactory("-dae +c"),
	SyllableFactory("-dho"),
	SyllableFactory("-eir"),
	SyllableFactory("-fi"),
	SyllableFactory("-fir"),
	SyllableFactory("-la"),
	SyllableFactory("-seh"),
	SyllableFactory("-sel"),
	SyllableFactory("-ev"),
	SyllableFactory("-fis"),
	SyllableFactory("-hu"),
	SyllableFactory("-ha"),
	SyllableFactory("-gar"),
	SyllableFactory("-gil"),
	SyllableFactory("-ka"),
	SyllableFactory("-kan"),
	SyllableFactory("-ya"),
	SyllableFactory("-za"),
	SyllableFactory("-zy"),
	SyllableFactory("-mara"),
	SyllableFactory("-mai +c"),
	SyllableFactory("-lue +c"),
	SyllableFactory("-ny"),
	SyllableFactory("-she"),
	SyllableFactory("-sum"),
	SyllableFactory("-syl"),
	SyllableFactory("ae +c -c"),
	SyllableFactory("ael -c"),
	SyllableFactory("dar"),
	SyllableFactory("deth +v"),
	SyllableFactory("dre -v"),
	SyllableFactory("drim -v"),
	SyllableFactory("dul"),
	SyllableFactory("ean -c"),
	SyllableFactory("el"),
	SyllableFactory("emar"),
	SyllableFactory("hal"),
	SyllableFactory("iat -c"),
	SyllableFactory("mah"),
	SyllableFactory("ten"),
	SyllableFactory("que -v +c"),
	SyllableFactory("ria"),
	SyllableFactory("rail"),
	SyllableFactory("ther"),
	SyllableFactory("thus"),
	SyllableFactory("thi"),
	SyllableFactory("san"),
	SyllableFactory("+ael -c"),
	SyllableFactory("+dar"),
	SyllableFactory("+deth"),
	SyllableFactory("+dre"),
	SyllableFactory("+drim"),
	SyllableFactory("+dul"),
	SyllableFactory("+ean -c"),
	SyllableFactory("+el"),
	SyllableFactory("+emar"),
	SyllableFactory("+nes"),
	SyllableFactory("+nin"),
	SyllableFactory("+oth"),
	SyllableFactory("+hal"),
	SyllableFactory("+iat"),
	SyllableFactory("+mah"),
	SyllableFactory("+ten"),
	SyllableFactory("+ther"),
	SyllableFactory("+thus"),
	SyllableFactory("+thi"),
	SyllableFactory("+ran"),
	SyllableFactory("+ath"),
	SyllableFactory("+ess"),
	SyllableFactory("+san"),
	SyllableFactory("+yth"),
	SyllableFactory("+las"),
	SyllableFactory("+lian"),
	SyllableFactory("+evar"),
}

// ElvenMap language Syllable Map
var ElvenMap = mapit(Elven)

// Fantasy language Syllables
var Fantasy = []Syllable{
	SyllableFactory("-a +c"),
	SyllableFactory("-ab"),
	SyllableFactory("-ac"),
	SyllableFactory("-ad"),
	SyllableFactory("-af"),
	SyllableFactory("-ak"),
	SyllableFactory("-am"),
	SyllableFactory("-an"),
	SyllableFactory("-ap"),
	SyllableFactory("-ar"),
	SyllableFactory("-as"),
	SyllableFactory("-at"),
	SyllableFactory("-aw"),
	SyllableFactory("-az"),
	SyllableFactory("-ael"),
	SyllableFactory("-ael"),
	SyllableFactory("-ao"),
	SyllableFactory("-aer"),
	SyllableFactory("-ash"),
	SyllableFactory("-arsh +v"),
	SyllableFactory("-ath"),
	SyllableFactory("-arg +v"),
	SyllableFactory("-arv +v"),
	SyllableFactory("-art +v"),
	SyllableFactory("-arn +v"),
	SyllableFactory("-ag"),
	SyllableFactory("-ang +v"),
	SyllableFactory("-anthr +v"),
	SyllableFactory("-ba +c"),
	SyllableFactory("-be +c"),
	SyllableFactory("-bi"),
	SyllableFactory("-bo +c"),
	SyllableFactory("-bu +c"),
	SyllableFactory("-beo +c"),
	SyllableFactory("-bra +c"),
	SyllableFactory("-bre +c"),
	SyllableFactory("-bei"),
	SyllableFactory("-bro +c"),
	SyllableFactory("-bru"),
	SyllableFactory("-breo +c"),
	SyllableFactory("-brao +c"),
	SyllableFactory("-da +c"),
	SyllableFactory("-de +c"),
	SyllableFactory("-di"),
	SyllableFactory("-do +c"),
	SyllableFactory("-du +c"),
	SyllableFactory("-dae +c"),
	SyllableFactory("-dai"),
	SyllableFactory("-dao +c"),
	SyllableFactory("-dra +c"),
	SyllableFactory("-dre +c"),
	SyllableFactory("-dri"),
	SyllableFactory("-dro +c"),
	SyllableFactory("-dash"),
	SyllableFactory("-desh"),
	SyllableFactory("-dosh"),
	SyllableFactory("-darr +v"),
	SyllableFactory("-dar"),
	SyllableFactory("-derr +v"),
	SyllableFactory("-der"),
	SyllableFactory("-dorr +v"),
	SyllableFactory("-dor"),
	SyllableFactory("-durr +v"),
	SyllableFactory("-dur"),
	SyllableFactory("-dran"),
	SyllableFactory("-dren"),
	SyllableFactory("-dron"),
	SyllableFactory("-drun"),
	SyllableFactory("-drav"),
	SyllableFactory("-drev"),
	SyllableFactory("-drov"),
	SyllableFactory("-dov"),
	SyllableFactory("-duv"),
	SyllableFactory("-darv +v"),
	SyllableFactory("-dorv +v"),
	SyllableFactory("-durv +v"),
	SyllableFactory("-eo +c"),
	SyllableFactory("-ei +c"),
	SyllableFactory("-ed"),
	SyllableFactory("-ga +c"),
	SyllableFactory("-go +c"),
	SyllableFactory("-gu +c"),
	SyllableFactory("-gra +c"),
	SyllableFactory("-gro +c"),
	SyllableFactory("-gru +c"),
	SyllableFactory("-garl"),
	SyllableFactory("-gorl"),
	SyllableFactory("-ha +c"),
	SyllableFactory("-he +c"),
	SyllableFactory("-hi +c"),
	SyllableFactory("-ho +c"),
	SyllableFactory("-hu +c"),
	SyllableFactory("-han"),
	SyllableFactory("-hun"),
	SyllableFactory("-hon"),
	SyllableFactory("-idr +v"),
	SyllableFactory("-igr +v"),
	SyllableFactory("-irn +v"),
	SyllableFactory("-ign +v"),
	SyllableFactory("-in"),
	SyllableFactory("-ins"),
	SyllableFactory("-intr +v"),
	SyllableFactory("-ka +c"),
	SyllableFactory("-ke +c"),
	SyllableFactory("-ki"),
	SyllableFactory("-ko +c"),
	SyllableFactory("-ku +c"),
	SyllableFactory("-kov"),
	SyllableFactory("-korv +v"),
	SyllableFactory("-kran"),
	SyllableFactory("-kren"),
	SyllableFactory("-kron"),
	SyllableFactory("-krun"),
	SyllableFactory("-karn"),
	SyllableFactory("-kern"),
	SyllableFactory("-korn"),
	SyllableFactory("-kurn"),
	SyllableFactory("-lod +v"),
	SyllableFactory("-lodd +v"),
	SyllableFactory("-la +c"),
	SyllableFactory("-lad +v"),
	SyllableFactory("-ladd +v"),
	SyllableFactory("-lor"),
	SyllableFactory("-lorn +v"),
	SyllableFactory("-llor"),
	SyllableFactory("-llorn +v"),
	SyllableFactory("-llorv +v"),
	SyllableFactory("-orv +v"),
	SyllableFactory("-orn +v"),
	SyllableFactory("-orgl +v"),
	SyllableFactory("-pa +c"),
	SyllableFactory("-pu +c"),
	SyllableFactory("-po +c"),
	SyllableFactory("-ra +c"),
	SyllableFactory("-re +c"),
	SyllableFactory("-ru +c"),
	SyllableFactory("-rab +v"),
	SyllableFactory("-rak"),
	SyllableFactory("-rob +v"),
	SyllableFactory("-rok"),
	SyllableFactory("-rub +v"),
	SyllableFactory("-ruk"),
	SyllableFactory("-stra +c"),
	SyllableFactory("-stre +c"),
	SyllableFactory("-sto +c"),
	SyllableFactory("-sar"),
	SyllableFactory("-sor"),
	SyllableFactory("-ser"),
	SyllableFactory("-tu +c"),
	SyllableFactory("-tuk"),
	SyllableFactory("-tuv +v"),
	SyllableFactory("-un"),
	SyllableFactory("-unn +v"),
	SyllableFactory("-und"),
	SyllableFactory("-ud"),
	SyllableFactory("-uk"),
	SyllableFactory("-va"),
	SyllableFactory("-vaa +c"),
	SyllableFactory("-ve +c"),
	SyllableFactory("-vo +c"),
	SyllableFactory("-vu +c"),
	SyllableFactory("-val"),
	SyllableFactory("-vel"),
	SyllableFactory("-vol"),
	SyllableFactory("-vul"),
	SyllableFactory("-vraal"),
	SyllableFactory("-vral"),
	SyllableFactory("-vrul"),
	SyllableFactory("-vratt +v"),
	SyllableFactory("-vrott +v"),
	SyllableFactory("-vrod +v"),
	SyllableFactory("-vrok +v"),
	SyllableFactory("-vork +v"),
	SyllableFactory("-vort +v"),
	SyllableFactory("-za +c"),
	SyllableFactory("-zaa +c"),
	SyllableFactory("-zar"),
	SyllableFactory("-zon"),
	SyllableFactory("-zoll +v"),
	SyllableFactory("ab -c"),
	SyllableFactory("ac -c"),
	SyllableFactory("ad -c"),
	SyllableFactory("af -c"),
	SyllableFactory("ak -c"),
	SyllableFactory("am -c"),
	SyllableFactory("an -c"),
	SyllableFactory("ap -c"),
	SyllableFactory("ar -c"),
	SyllableFactory("as -c"),
	SyllableFactory("at -c"),
	SyllableFactory("aw -c"),
	SyllableFactory("az -c"),
	SyllableFactory("ael -c"),
	SyllableFactory("ael -c"),
	SyllableFactory("ao -c"),
	SyllableFactory("aer -c"),
	SyllableFactory("ba"),
	SyllableFactory("be"),
	SyllableFactory("bi"),
	SyllableFactory("bo"),
	SyllableFactory("bu"),
	SyllableFactory("beo"),
	SyllableFactory("bra"),
	SyllableFactory("bre"),
	SyllableFactory("bei"),
	SyllableFactory("bro"),
	SyllableFactory("bru"),
	SyllableFactory("breo"),
	SyllableFactory("brao"),
	SyllableFactory("da"),
	SyllableFactory("de"),
	SyllableFactory("di"),
	SyllableFactory("do"),
	SyllableFactory("du"),
	SyllableFactory("dae"),
	SyllableFactory("dai"),
	SyllableFactory("dao"),
	SyllableFactory("dra"),
	SyllableFactory("dre"),
	SyllableFactory("dri"),
	SyllableFactory("dro"),
	SyllableFactory("dash"),
	SyllableFactory("desh"),
	SyllableFactory("dosh"),
	SyllableFactory("darr"),
	SyllableFactory("dar"),
	SyllableFactory("derr"),
	SyllableFactory("der"),
	SyllableFactory("dorr"),
	SyllableFactory("dor"),
	SyllableFactory("durr"),
	SyllableFactory("dur"),
	SyllableFactory("dran"),
	SyllableFactory("dren"),
	SyllableFactory("dron"),
	SyllableFactory("drun"),
	SyllableFactory("drav"),
	SyllableFactory("drev"),
	SyllableFactory("drov"),
	SyllableFactory("dov"),
	SyllableFactory("duv"),
	SyllableFactory("darv"),
	SyllableFactory("dorv"),
	SyllableFactory("durv"),
	SyllableFactory("eo -c +c"),
	SyllableFactory("ei -c"),
	SyllableFactory("ed -c"),
	SyllableFactory("ga -v +c"),
	SyllableFactory("go -v +c"),
	SyllableFactory("gu -v +c"),
	SyllableFactory("gra -v"),
	SyllableFactory("gro -v"),
	SyllableFactory("gru -v +c"),
	SyllableFactory("garl -v"),
	SyllableFactory("gorl -v"),
	SyllableFactory("ha -v +c"),
	SyllableFactory("he -v +c"),
	SyllableFactory("hi -v"),
	SyllableFactory("ho -v +c"),
	SyllableFactory("hu -v +c"),
	SyllableFactory("han -v"),
	SyllableFactory("hun -v"),
	SyllableFactory("hon -v"),
	SyllableFactory("idr -c +v"),
	SyllableFactory("igr -c +v"),
	SyllableFactory("irn -c +v"),
	SyllableFactory("ign -c +v"),
	SyllableFactory("in"),
	SyllableFactory("ins"),
	SyllableFactory("intr -c"),
	SyllableFactory("ka -v +c"),
	SyllableFactory("ke -v +c"),
	SyllableFactory("ki -v"),
	SyllableFactory("ko -v +c"),
	SyllableFactory("ku -v +c"),
	SyllableFactory("kov -v +v"),
	SyllableFactory("korv -v +v"),
	SyllableFactory("kran -v +v"),
	SyllableFactory("kren -v +v"),
	SyllableFactory("kron -v +v"),
	SyllableFactory("krun -v +v"),
	SyllableFactory("karn -v +v"),
	SyllableFactory("kern -v +v"),
	SyllableFactory("korn -v +v"),
	SyllableFactory("kurn -v +v"),
	SyllableFactory("lod -v"),
	SyllableFactory("lodd -v"),
	SyllableFactory("la -v +c"),
	SyllableFactory("lad -v"),
	SyllableFactory("ladd  -v +v"),
	SyllableFactory("lor  -v"),
	SyllableFactory("lorn -v +v"),
	SyllableFactory("orv -c +v"),
	SyllableFactory("orn -c +v"),
	SyllableFactory("orgl -c +v"),
	SyllableFactory("pa -v +c"),
	SyllableFactory("pu -v +c"),
	SyllableFactory("po -v +c"),
	SyllableFactory("ra -v +c"),
	SyllableFactory("re -v +c"),
	SyllableFactory("ru -v +c"),
	SyllableFactory("rab -v +c"),
	SyllableFactory("rak -v +c"),
	SyllableFactory("rob -v +c"),
	SyllableFactory("rok -v"),
	SyllableFactory("rub -v +c"),
	SyllableFactory("ruk -v"),
	SyllableFactory("stra -v +c"),
	SyllableFactory("stre -v +c"),
	SyllableFactory("sto -v +c"),
	SyllableFactory("sar -v"),
	SyllableFactory("sor -v"),
	SyllableFactory("serr -v +c"),
	SyllableFactory("tu -v +c"),
	SyllableFactory("tuk -v"),
	SyllableFactory("tuv -v +c"),
	SyllableFactory("un -c"),
	SyllableFactory("unn -c +v"),
	SyllableFactory("und -c +v"),
	SyllableFactory("ud -c +v"),
	SyllableFactory("uk -c"),
	SyllableFactory("va -v +c"),
	SyllableFactory("vaa -v +c"),
	SyllableFactory("ve -v +c"),
	SyllableFactory("vo -v +c"),
	SyllableFactory("vu -v +c"),
	SyllableFactory("val -v"),
	SyllableFactory("vel -v"),
	SyllableFactory("vol -v"),
	SyllableFactory("vul -v"),
	SyllableFactory("vral -v +v"),
	SyllableFactory("vrul -v +v"),
	SyllableFactory("+al -c"),
	SyllableFactory("+ol -c"),
	SyllableFactory("+ul -c"),
	SyllableFactory("+ath -c"),
	SyllableFactory("+oth -c"),
	SyllableFactory("+an -c"),
	SyllableFactory("+un -c"),
	SyllableFactory("+en -c"),
	SyllableFactory("+iel -c"),
	SyllableFactory("+iol -c"),
	SyllableFactory("+iul -c"),
	SyllableFactory("+at -c"),
	SyllableFactory("+ut -c"),
	SyllableFactory("+ll -v"),
	SyllableFactory("+d -v"),
	SyllableFactory("+st -v"),
	SyllableFactory("+ss -v"),
	SyllableFactory("+s"),
}

// FantasyMap language Syllable Map
var FantasyMap = mapit(Fantasy)

// Goblin language Syllables
var Goblin = []Syllable{
	SyllableFactory("-waa +c"),
	SyllableFactory("-boo +c"),
	SyllableFactory("-gar"),
	SyllableFactory("-bar"),
	SyllableFactory("-dar"),
	SyllableFactory("-jar"),
	SyllableFactory("-var"),
	SyllableFactory("-kra"),
	SyllableFactory("-gra"),
	SyllableFactory("-dra"),
	SyllableFactory("-zra"),
	SyllableFactory("-gob"),
	SyllableFactory("-dob"),
	SyllableFactory("-rob"),
	SyllableFactory("-fob"),
	SyllableFactory("-zob"),
	SyllableFactory("-rag"),
	SyllableFactory("-nag"),
	SyllableFactory("-dag"),
	SyllableFactory("bra"),
	SyllableFactory("ga"),
	SyllableFactory("da"),
	SyllableFactory("do"),
	SyllableFactory("go"),
	SyllableFactory("ze"),
	SyllableFactory("sha"),
	SyllableFactory("naz"),
	SyllableFactory("zub"),
	SyllableFactory("zu"),
	SyllableFactory("na"),
	SyllableFactory("gor"),
	SyllableFactory("boo +c"),
	SyllableFactory("+byr"),
	SyllableFactory("+gyr"),
	SyllableFactory("+dyr"),
	SyllableFactory("+vyr"),
	SyllableFactory("+zyr"),
	SyllableFactory("+yr -c"),
	SyllableFactory("+zog"),
	SyllableFactory("+rog"),
	SyllableFactory("+gog"),
	SyllableFactory("+og -c"),
	SyllableFactory("+gul"),
	SyllableFactory("+dul"),
	SyllableFactory("+bul"),
	SyllableFactory("+rul"),
	SyllableFactory("+ul -c"),
	SyllableFactory("+rgh -v"),
}

// GoblinMap language Syllable Map
var GoblinMap = mapit(Goblin)

// Roman language Syllables
var Roman = []Syllable{
	SyllableFactory("-a"),
	SyllableFactory("-al"),
	SyllableFactory("-au +c"),
	SyllableFactory("-an"),
	SyllableFactory("-ba"),
	SyllableFactory("-be"),
	SyllableFactory("-bi"),
	SyllableFactory("-br +v"),
	SyllableFactory("-da"),
	SyllableFactory("-di"),
	SyllableFactory("-do"),
	SyllableFactory("-du"),
	SyllableFactory("-e"),
	SyllableFactory("-eu +c"),
	SyllableFactory("-fa"),
	SyllableFactory("bi -v"),
	SyllableFactory("be -v"),
	SyllableFactory("bo -v"),
	SyllableFactory("bu -v"),
	SyllableFactory("nul +v"),
	SyllableFactory("gu -v"),
	SyllableFactory("da -v"),
	SyllableFactory("au +c -c"),
	SyllableFactory("fri-v"),
	SyllableFactory("gus -v"),
	SyllableFactory("+tus"),
	SyllableFactory("+lus"),
	SyllableFactory("+lius"),
	SyllableFactory("+nus"),
	SyllableFactory("+es"),
	SyllableFactory("+ius -c"),
	SyllableFactory("+cus"),
	SyllableFactory("+tor"),
	SyllableFactory("+cio"),
	SyllableFactory("+tin"),
}

// RomanMap language Syllable Map
var RomanMap = mapit(Roman)
