---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: 1.8}

inputs:
- name: resource-goname
  path: gopath/src/github.com/PassengerTicketing/goname

run:
  path: resource-goname/ci/scripts/task_run_tests.sh
