---
resources:
- name: resource-goname
  type: git
  source:
    branch: master
    uri: https://github.com/folkengine/goname.git

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: resource-goname
    trigger: true
  - task: unit-tests
    file: resource-goname/ci/xunit.yaml

