resources:
- name: goname
  type: git
  source:
    branch: master
    uri: https://github.com/folkengine/goname.git

jobs:
- name: unit-tests
  plan:
  - get: goname
    trigger: true
  - task: unit-tests
    file: resource-goname/build.yaml
